//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSFuncionario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class func
    {
        public int codFuncionario { get; set; }
        public string nome { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime dataNascimento { get; set; }
        public decimal salario { get; set; }
        public string atividades { get; set; }

        public string Atividade
        {
            get
            {
                if (this.atividades.Length > 150)
                {
                    return this.atividades.Substring(0, 150) + "...";
                }
                else
                {
                    return this.atividades;
                }
            }
        }
    }
}
